### ISSUE TITLE
Ceylon Vert.x docs contain errors

### ISSUE THREAD

**Issue by lukehutch** [vietj/ceylon-vertx#24]
I started working through the Vert.x [core](http://vertx.io/docs/vertx-core/ceylon/) and [web](http://vertx.io/docs/vertx-web/ceylon/) docs, but keep running into issues. I filed a bug in the vert-x3 site, but is the vietj/ceylon-vertx tracker the correct one instead? See:
[https://github.com/vert-x3/vertx-web/issues/282](https://github.com/vert-x3/vertx-web/issues/282)

**Comment by vietj** [comment]
hi, this repo https://github.com/vert-x3/vertx-lang-ceylon is the correct place to report it

**Comment by lukehutch** [comment]
Thanks, closing this report.
